In [ ]:
import pandas as pd
import numpy as np
import joblib
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.pipeline import make_pipeline,Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer
from xgboost import XGBRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score,root_mean_squared_error,mean_squared_error

In [3]:
df = pd.read_csv('housing.csv')
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [4]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [6]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [7]:
#Split Features and Labels
X = df.drop('median_house_value',axis=1)
Y = df['median_house_value']

In [8]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [9]:
num_feat = X_train.select_dtypes(include=[np.number]).columns.tolist()
cat_feat = X_train.select_dtypes(exclude=[np.number]).columns.tolist()
num_feat,cat_feat

(['longitude',
  'latitude',
  'housing_median_age',
  'total_rooms',
  'total_bedrooms',
  'population',
  'households',
  'median_income'],
 ['ocean_proximity'])

In [10]:
num_pipe =make_pipeline(SimpleImputer(strategy='median'),StandardScaler())
cat_pipe =make_pipeline(OneHotEncoder(handle_unknown='ignore'))
preprocessor = ColumnTransformer([
    ('num',num_pipe,num_feat),
    ('cat',cat_pipe,cat_feat)
])

In [11]:
rf_pipe = make_pipeline(preprocessor,RandomForestRegressor(random_state=42))
rf_pipe.fit(X_train,Y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('standardscaler',
                                                                   StandardScaler())]),
                                                  ['longitude', 'latitude',
                                                   'housing_median_age',
                                                   'total_rooms',
                                                   'total_bedrooms',
                                                   'population', 'households',
                                                   'median_income']),
                                                 ('cat',
                                                  Pipeline(steps=[('onehotencoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['ocean_proximity'])])),
                ('randomforestregressor',
                 RandomForestRegressor(random_state=42))])

In [12]:
rf_pred = rf_pipe.predict(X_test)

In [15]:
rf_r2 = round(r2_score(Y_test,rf_pred),3)
rf_rmse = round(root_mean_squared_error(Y_test,rf_pred),2)
rf_mse = round(mean_squared_error(Y_test,rf_pred),2)
rf_r2,rf_rmse,rf_mse

(0.817, 48941.7, 2395290032.47)

In [18]:
xgb_pipe = make_pipeline(preprocessor,XGBRegressor())
xgb_pipe.fit(X_train,Y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('standardscaler',
                                                                   StandardScaler())]),
                                                  ['longitude', 'latitude',
                                                   'housing_median_age',
                                                   'total_rooms',
                                                   'total_bedrooms',
                                                   'population', 'households',
                                                   'median_income']),
                                                 ('cat',
                                                  Pipeline(steps=[('onehotencoder',
                                                                   OneHotEnc...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=None,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=None, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=None, n_jobs=None,
                              num_parallel_tree=None, ...))])

In [19]:
xgb_pred = xgb_pipe.predict(X_test)

In [23]:
xgb_r2 = round(r2_score(Y_test,xgb_pred),3)
xgb_rmse =round(root_mean_squared_error(Y_test,xgb_pred),2)
xgb_mse =round(mean_squared_error(Y_test,xgb_pred),2)
xgb_r2,xgb_rmse,xgb_mse

(0.829, 47350.72, 2242090716.72)

In [29]:
grid_xgb = GridSearchCV (
    estimator=xgb_pipe,
    param_grid= {
        "xgbregressor__n_estimators":[100,150,200],
        'xgbregressor__max_depth':[5,10,None],
        'xgbregressor__learning_rate':[0.1,0.05],
        'xgbregressor__subsample':[0.8,0.7],
        'xgbregressor__colsample_bytree':[0.6,0.7]
    },
    cv=5
)
grid_xgb.fit(X_train,Y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(transformers=[('num',
                                                                         Pipeline(steps=[('simpleimputer',
                                                                                          SimpleImputer(strategy='median')),
                                                                                         ('standardscaler',
                                                                                          StandardScaler())]),
                                                                         ['longitude',
                                                                          'latitude',
                                                                          'housing_median_age',
                                                                          'total_rooms',
                                                                          'total_bedrooms',
                                                                          'population',
                                                                          'households',
                                                                          'median_income']),
                                                                        ('cat',
                                                                         Pipeline(steps...
                                                     min_child_weight=None,
                                                     missing=nan,
                                                     monotone_constraints=None,
                                                     multi_strategy=None,
                                                     n_estimators=None,
                                                     n_jobs=None,
                                                     num_parallel_tree=None, ...))]),
             param_grid={'xgbregressor__colsample_bytree': [0.6, 0.7],
                         'xgbregressor__learning_rate': [0.1, 0.05],
                         'xgbregressor__max_depth': [5, 10, None],
                         'xgbregressor__n_estimators': [100, 150, 200],
                         'xgbregressor__subsample': [0.8, 0.7]})

In [31]:
best_model = grid_xgb.best_estimator_
best_model_pred = best_model.predict(X_test)
best_model_r2 = round(r2_score(Y_test,best_model_pred),3)
best_model_rmse = round(root_mean_squared_error(Y_test,best_model_pred),2)
best_model_mse = round(mean_squared_error(Y_test,best_model_pred),2)
best_model_r2,best_model_rmse,best_model_mse

(0.842, 45525.61, 2072580861.5)

In [34]:
Model_Comparison = pd.DataFrame({
    "Model":['RandomForestRegressor','XGBRegressor','TunedXGB'],
    'R2SCORE':[0.817,0.829,0.842],
    'RMSE':[48941.7,47350.72,45525.51],
    'MSE':[2395290032.47,2242090716.72,2072580861.5]
})
Model_Comparison

                   Model  R2SCORE      RMSE           MSE
0  RandomForestRegressor    0.817  48941.70  2.395290e+09
1           XGBRegressor    0.829  47350.72  2.242091e+09
2               TunedXGB    0.842  45525.51  2.072581e+09

In [35]:
MODEL_FILE = 'model.pkl'
Model ={
    'rf':rf_pipe,
    'xgb':xgb_pipe,
    'best_model':best_model
}
joblib.dump(Model,MODEL_FILE)
print("Model Saved")

Model Saved